name: Claude Computer Use Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb tint2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit anthropic httpx boto3 google-auth

    - name: Setup Configuration
      run: |
        mkdir -p ~/.anthropic
        echo "${{ secrets.ANTHROPIC_API_KEY }}" > ~/.anthropic/api_key
        chmod 700 ~/.anthropic
        chmod 600 ~/.anthropic/api_key

    - name: Debug Directory
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "GitHub Workspace:"
        echo $GITHUB_WORKSPACE
        ls -la $GITHUB_WORKSPACE

    - name: Start Services
      run: |
        echo "Making script executable..."
        chmod +x $GITHUB_WORKSPACE/start_all.sh || echo "chmod failed"
        echo "Running script from workspace..."
        bash $GITHUB_WORKSPACE/start_all.sh &
        sleep 5

    - name: Run Streamlit
      run: |
        streamlit run app.py &
        sleep 10  # Give Streamlit time to start
