name: Claude Computer Use Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb tint2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit anthropic httpx boto3 google-auth

    - name: Setup Configuration
      run: |
        mkdir -p ~/.anthropic
        echo "${{ secrets.ANTHROPIC_API_KEY }}" > ~/.anthropic/api_key
        chmod 700 ~/.anthropic
        chmod 600 ~/.anthropic/api_key

    - name: Debug Files and Permissions
      run: |
        echo "==== Current Location ===="
        pwd
        echo "==== Repository Contents ===="
        ls -la
        echo "==== Parent Directory ===="
        ls -la ..
        echo "==== Full Path Check ===="
        find . -name "start_all.sh"

    - name: Start Services
      run: |
        echo "==== Attempting to locate start_all.sh ===="
        if [ -f "start_all.sh" ]; then
          echo "File exists in current directory"
          chmod +x start_all.sh
          ./start_all.sh &
        elif [ -f "$GITHUB_WORKSPACE/start_all.sh" ]; then
          echo "File exists in GITHUB_WORKSPACE"
          chmod +x $GITHUB_WORKSPACE/start_all.sh
          $GITHUB_WORKSPACE/start_all.sh &
        else
          echo "start_all.sh not found!"
          echo "Current directory contents:"
          ls -la
        fi
        sleep 5

    - name: Run Streamlit
      run: |
        streamlit run app.py &
        sleep 10  # Give Streamlit time to start
